#include <limits.h>
#include "include/core/platform.h"
#include "include/api/api.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/threaded/scheduler.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
#include "include/core/federated/federate.h"
#include "include/core/federated/net_common.h"
#include "pythontarget.h"
// Code generated by the Lingua Franca compiler from:
// file://mnt/c/Users/jacky/Desktop/simple_multi/fed-gen/Main/src/federate__server.lf
#define LOG_LEVEL 4
#define TARGET_FILES_DIRECTORY "/mnt/c/Users/jacky/Desktop/simple_multi/fed-gen/Main/src-gen/federate__server"
int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
const char* _lf_default_argv[] = { "dummy", "-k", "true", "-o", "10", "sec" };
void _lf_set_default_command_line_options() {
        default_argc = 6;
        default_argv = _lf_default_argv;
}
#include "_serverreactor.h"
#include "_federate__server_main.h"
typedef enum {
    federate__server_main,
    _num_enclaves
} _enclave_id;
// The global array of environments associated with each enclave
environment_t envs[_num_enclaves];
// 'Create' and initialize the environments in the program
void _lf_create_environments() {
    environment_init(&envs[federate__server_main],federate__server_main,_lf_number_of_workers,0,1,0,0,4,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) envs;
   return _num_enclaves;
}
#include "include/_federate__server_preamble.h"
// No watchdogs found.
typedef void watchdog_t;
watchdog_t* _lf_watchdogs = NULL;
int _lf_watchdog_count = 0;
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _federate__server_main_main_self_t* federate__server_main_self[1];
    SUPPRESS_UNUSED_WARNING(federate__server_main_self);
    _serverreactor_self_t* federate__server_server_self[1];
    SUPPRESS_UNUSED_WARNING(federate__server_server_self);
    // ***** Start initializing federate__server of class federate__server
    federate__server_main_self[0] = new__federate__server_main();
    federate__server_main_self[0]->base.environment = &envs[federate__server_main];
    federate__server_main_self[0]->_lf_name = "federate__server_main_lf";
    SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    // Initializing action federate__server.inputControlReactionTrigger
    federate__server_main_self[0]->_lf__inputControlReactionTrigger.offset = 0;
    federate__server_main_self[0]->_lf__inputControlReactionTrigger.period = -1;
    federate__server_main_self[0]->_lf__inputControlReactionTrigger.mode = NULL;
    // Initializing action federate__server.networkMessage
    federate__server_main_self[0]->_lf__networkMessage.offset = 0;
    federate__server_main_self[0]->_lf__networkMessage.period = -1;
    federate__server_main_self[0]->_lf__networkMessage.mode = NULL;
    _lf_initialize_template((token_template_t*)
            &(federate__server_main_self[0]->_lf__inputControlReactionTrigger),
    0);
    federate__server_main_self[0]->_lf__inputControlReactionTrigger.status = absent;
    _lf_initialize_template((token_template_t*)
            &(federate__server_main_self[0]->_lf__networkMessage),
    0);
    federate__server_main_self[0]->_lf__networkMessage.status = absent;
    federate__server_main_self[0]->_lf__reaction_0.deadline = NEVER;
    federate__server_main_self[0]->_lf__reaction_1.deadline = NEVER;
    federate__server_main_self[0]->_lf__reaction_2.deadline = NEVER;
    {
        // ***** Start initializing federate__server.server of class ServerReactor
        federate__server_server_self[0] = new__serverreactor();
        federate__server_server_self[0]->base.environment = &envs[federate__server_main];
        federate__server_server_self[0]->_lf_name = "federate__server_server_lf";
        federate__server_server_self[0]->_lf_py_reaction_function_0 = 
        get_python_function("__main__", 
            federate__server_server_self[0]->_lf_name,
            0,
            "reaction_function_0");
        if(federate__server_server_self[0]->_lf_py_reaction_function_0 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_0");
        }
        federate__server_server_self[0]->_lf_py_reaction_function_1 = 
        get_python_function("__main__", 
            federate__server_server_self[0]->_lf_name,
            0,
            "reaction_function_1");
        if(federate__server_server_self[0]->_lf_py_reaction_function_1 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_1");
        }
        // width of -2 indicates that it is not a multiport.
        federate__server_server_self[0]->_lf_out_parameter_width = -2;
        // width of -2 indicates that it is not a multiport.
        federate__server_server_self[0]->_lf_in_parameter_width = -2;
        envs[federate__server_main].startup_reactions[startup_reaction_count[federate__server_main]++] = &federate__server_server_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
        federate__server_server_self[0]->_lf__reaction_0.deadline = NEVER;
        federate__server_server_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing federate__server.server
    }
    //***** End initializing federate__server
    // **** Start deferred initialize for federate__server
    {
        federate__server_main_self[0]->_lf__reaction_0.name = "federate__server reaction 0";
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of federate__server.
        federate__server_main_self[0]->_lf__reaction_0.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        federate__server_main_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &federate__server_main_self[0]->base.allocations);
        federate__server_main_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &federate__server_main_self[0]->base.allocations);
        federate__server_main_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &federate__server_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                federate__server_main_self[0]->_lf__reaction_0.output_produced[count++] = &federate__server_main_self[0]->_lf_server.in_parameter.is_present;
            }
        }
        
        // ** End initialization for reaction 0 of federate__server
        federate__server_main_self[0]->_lf__reaction_1.name = "federate__server reaction 1";
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of federate__server.
        federate__server_main_self[0]->_lf__reaction_1.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        federate__server_main_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &federate__server_main_self[0]->base.allocations);
        federate__server_main_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &federate__server_main_self[0]->base.allocations);
        federate__server_main_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &federate__server_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                federate__server_main_self[0]->_lf__reaction_1.output_produced[count++] = &federate__server_main_self[0]->_lf_server.in_parameter.is_present;
            }
        }
        
        // ** End initialization for reaction 1 of federate__server
        federate__server_main_self[0]->_lf__reaction_2.name = "federate__server reaction 2";
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_2 of federate__server.
        federate__server_main_self[0]->_lf__reaction_2.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 2 of federate__server
        // **** Start deferred initialize for federate__server.server
        {
            federate__server_server_self[0]->_lf__reaction_0.name = "federate__server.server reaction 0";
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of federate__server.server.
            federate__server_server_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            federate__server_server_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &federate__server_server_self[0]->base.allocations);
            federate__server_server_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &federate__server_server_self[0]->base.allocations);
            federate__server_server_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &federate__server_server_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    federate__server_server_self[0]->_lf__reaction_0.output_produced[count++] = &federate__server_server_self[0]->_lf_out_parameter.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of federate__server.server
            federate__server_server_self[0]->_lf__reaction_1.name = "federate__server.server reaction 1";
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of federate__server.server.
            federate__server_server_self[0]->_lf__reaction_1.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            federate__server_server_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &federate__server_server_self[0]->base.allocations);
            federate__server_server_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &federate__server_server_self[0]->base.allocations);
            federate__server_server_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &federate__server_server_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    federate__server_server_self[0]->_lf__reaction_1.output_produced[count++] = &federate__server_server_self[0]->_lf_out_parameter.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of federate__server.server
        }
        // **** End of deferred initialize for federate__server.server
    }
    // **** End of deferred initialize for federate__server
    // **** Start non-nested deferred initialize for federate__server
    // Set number of destination reactors for port server.in_parameter.
    // Iterate over range federate__server.server.in_parameter(0,1)->[federate__server.server.in_parameter(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        federate__server_main_self[src_runtime]->_lf_server.in_parameter._base.num_destinations = 1;
        federate__server_main_self[src_runtime]->_lf_server.in_parameter._base.source_reactor = (self_base_t*)federate__server_main_self[src_runtime];
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range federate__server.server.in_parameter(0,1)->[federate__server.server.in_parameter(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 0 of federate__server triggers 1 downstream reactions
            // through port federate__server.server.in_parameter.
            federate__server_main_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of federate__server, allocate an
            // array of trigger pointers for downstream reactions through port federate__server.server.in_parameter
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &federate__server_main_self[src_runtime]->base.allocations); 
            federate__server_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges federate__server.server.in_parameter(0,1)->[federate__server.server.in_parameter(0,1)] and federate__server.server.in_parameter(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range federate__server.server.in_parameter(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port federate__server.server.in_parameter's trigger struct.
                federate__server_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &federate__server_server_self[dst_runtime]->_lf__in_parameter;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range federate__server.server.in_parameter(0,1)->[federate__server.server.in_parameter(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of federate__server triggers 1 downstream reactions
            // through port federate__server.server.in_parameter.
            federate__server_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of federate__server, allocate an
            // array of trigger pointers for downstream reactions through port federate__server.server.in_parameter
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &federate__server_main_self[src_runtime]->base.allocations); 
            federate__server_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges federate__server.server.in_parameter(0,1)->[federate__server.server.in_parameter(0,1)] and federate__server.server.in_parameter(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range federate__server.server.in_parameter(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port federate__server.server.in_parameter's trigger struct.
                federate__server_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &federate__server_server_self[dst_runtime]->_lf__in_parameter;
            }
        }
    }
    // **** Start non-nested deferred initialize for federate__server.server
    // For reference counting, set num_destinations for port federate__server.server.out_parameter.
    // Iterate over range federate__server.server.out_parameter(0,1)->[federate__server.server.out_parameter(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        federate__server_server_self[src_runtime]->_lf_out_parameter._base.num_destinations = 1;
        federate__server_server_self[src_runtime]->_lf_out_parameter._base.source_reactor = (self_base_t*)federate__server_server_self[src_runtime];
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range federate__server.server.out_parameter(0,1)->[federate__server.server.out_parameter(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 0 of federate__server.server triggers 1 downstream reactions
            // through port federate__server.server.out_parameter.
            federate__server_server_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of federate__server.server, allocate an
            // array of trigger pointers for downstream reactions through port federate__server.server.out_parameter
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &federate__server_server_self[src_runtime]->base.allocations); 
            federate__server_server_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges federate__server.server.out_parameter(0,1)->[federate__server.server.out_parameter(0,1)] and federate__server.server.out_parameter(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range federate__server.server.out_parameter(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Port federate__server.server.out_parameter has reactions in its parent's parent.
                // Point to the trigger struct for those reactions.
                federate__server_server_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &federate__server_main_self[dst_runtime]->_lf_server.out_parameter_trigger;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range federate__server.server.out_parameter(0,1)->[federate__server.server.out_parameter(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of federate__server.server triggers 1 downstream reactions
            // through port federate__server.server.out_parameter.
            federate__server_server_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of federate__server.server, allocate an
            // array of trigger pointers for downstream reactions through port federate__server.server.out_parameter
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &federate__server_server_self[src_runtime]->base.allocations); 
            federate__server_server_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges federate__server.server.out_parameter(0,1)->[federate__server.server.out_parameter(0,1)] and federate__server.server.out_parameter(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range federate__server.server.out_parameter(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Port federate__server.server.out_parameter has reactions in its parent's parent.
                // Point to the trigger struct for those reactions.
                federate__server_server_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &federate__server_main_self[dst_runtime]->_lf_server.out_parameter_trigger;
            }
        }
    }
    // **** End of non-nested deferred initialize for federate__server.server
    // **** End of non-nested deferred initialize for federate__server
    // Connect inputs and outputs for reactor federate__server.
    // Connect inputs and outputs for reactor federate__server.server.
    // Connect federate__server.server.in_parameter(0,1)->[federate__server.server.in_parameter(0,1)] to port federate__server.server.in_parameter(0,1)
    // Iterate over ranges federate__server.server.in_parameter(0,1)->[federate__server.server.in_parameter(0,1)] and federate__server.server.in_parameter(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range federate__server.server.in_parameter(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            federate__server_server_self[dst_runtime]->_lf_in_parameter = (_serverreactor_in_parameter_t*)&federate__server_main_self[src_runtime]->_lf_server.in_parameter;
        }
    }
    // Connect federate__server.server.out_parameter(0,1)->[federate__server.server.out_parameter(0,1)] to port federate__server.server.out_parameter(0,1)
    // Iterate over ranges federate__server.server.out_parameter(0,1)->[federate__server.server.out_parameter(0,1)] and federate__server.server.out_parameter(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range federate__server.server.out_parameter(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            federate__server_main_self[dst_runtime]->_lf_server.out_parameter = (_serverreactor_out_parameter_t*)&federate__server_server_self[src_runtime]->_lf_out_parameter;
        }
    }
    {
    }
    // Add port federate__server.server.in_parameter to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[federate__server_main].is_present_fields[0 + count] = &federate__server_main_self[0]->_lf_server.in_parameter.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[federate__server_main]._lf_intended_tag_fields[0 + count] = &federate__server_main_self[0]->_lf_server.in_parameter.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    {
        // Add action federate__server.inputControlReactionTrigger to array of is_present fields.
        envs[federate__server_main].is_present_fields[1] 
                = &federate__server_main_self[0]->_lf_inputControlReactionTrigger.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action federate__server.inputControlReactionTrigger to array of intended_tag fields.
        envs[federate__server_main]._lf_intended_tag_fields[1] 
                = &federate__server_main_self[0]->_lf_inputControlReactionTrigger.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action federate__server.networkMessage to array of is_present fields.
        envs[federate__server_main].is_present_fields[2] 
                = &federate__server_main_self[0]->_lf_networkMessage.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action federate__server.networkMessage to array of intended_tag fields.
        envs[federate__server_main]._lf_intended_tag_fields[2] 
                = &federate__server_main_self[0]->_lf_networkMessage.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port federate__server.server.out_parameter to array of is_present fields.
            envs[federate__server_main].is_present_fields[3 + count] = &federate__server_server_self[0]->_lf_out_parameter.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port federate__server.server.out_parameter to array of intended_tag fields.
            envs[federate__server_main]._lf_intended_tag_fields[3 + count] = &federate__server_server_self[0]->_lf_out_parameter.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    // Set reaction priorities for ReactorInstance federate__server
    {
        federate__server_main_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        federate__server_main_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
        federate__server_main_self[0]->_lf__reaction_1.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        federate__server_main_self[0]->_lf__reaction_1.index = 0xffffffffffff0000LL;
        federate__server_main_self[0]->_lf__reaction_2.chain_id = 1;
        // index is the OR of level 2 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        federate__server_main_self[0]->_lf__reaction_2.index = 0xffffffffffff0002LL;
        // Set reaction priorities for ReactorInstance federate__server.server
        {
            federate__server_server_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            federate__server_server_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            federate__server_server_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            federate__server_server_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
        }
    }
    // Initialize the scheduler
    size_t num_reactions_per_level[3] = 
        {3, 1, 1};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 3};
    lf_sched_init(
        &envs[federate__server_main],
        envs[federate__server_main].num_workers,
        &sched_params
    );
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&envs[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED
}
#ifndef FEDERATED
void terminate_execution(environment_t* env) {}
#endif
